services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: fsw-barber
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=root
      - POSTGRESQL_DATABASE=fsw-barber
