import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import './globals.css'
import { Footer } from './_components/footer'
import { Toaster } from './_components/ui/toaster'
import { AuthProvider } from './_providers/auth'
import { Header } from './_components/header'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${nunito.className}`}>
        <AuthProvider>
          <Header />

          <main className="flex h-full flex-col">
            <div className="flex-1">{children}</div>
            <Footer />
          </main>
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  )
}
